# otel-collector-config.yaml

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: 'api.honeycomb.io:443' # US instance
    #endpoint: "api.eu1.honeycomb.io:443" # EU instance
    headers:
      'x-honeycomb-team': ${env:HONEYCOMB_API_KEY}
  otlp/metrics:
    endpoint: 'api.honeycomb.io:443' # US instance
    #endpoint: "api.eu1.honeycomb.io:443" # EU instance
    headers:
      'x-honeycomb-dataset': 'movieswithfriends'
      'x-honeycomb-team': ${env:HONEYCOMB_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
