version: "3.0"
services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: myuser
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE_NAME: movies
  db:
    image: postgres:bullseye
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
