version: "3.0"
services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/go/src/app
    environment:
      DB_USERNAME: myuser
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE_NAME: movies
    ports:
      - 8080:8080
  db:
    image: postgres:bullseye
    restart: always
    volumes:
      - ./_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
