#! /bin/bash
POSTGRES="psql -U ${POSTGRES_USER} ${POSTGRES_DB}"

$POSTGRES <<EOSQL
-- First, create the migration user with full access
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${MIGRATION_USER}') THEN
    CREATE USER ${MIGRATION_USER} WITH PASSWORD '${MIGRATION_PASSWORD}';
  END IF;
END
\$\$;

-- Create the application user with restricted access
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${APP_USER}') THEN
    CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  END IF;
END
\$\$;

-- Connect to the specific database
\c ${POSTGRES_DB};

-- Grant necessary privileges to migration_user
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${MIGRATION_USER};
GRANT ALL ON SCHEMA public TO "$MIGRATION_USER";
ALTER USER ${MIGRATION_USER} CREATEDB;  -- Allows creation of new databases
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    GRANT ALL PRIVILEGES ON TABLES TO ${MIGRATION_USER};
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    GRANT ALL PRIVILEGES ON SEQUENCES TO ${MIGRATION_USER};
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    GRANT ALL PRIVILEGES ON FUNCTIONS TO ${MIGRATION_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${MIGRATION_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${MIGRATION_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${MIGRATION_USER};

-- Grant restricted privileges to app_user
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};
GRANT USAGE ON SCHEMA public TO ${APP_USER};

-- Grant CRUD permissions on all existing tables to app_user
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${APP_USER};

-- Set default privileges for future tables/sequences created by migration_user
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};

    -- Revoke ability to create new tables/schemas from app_user
REVOKE CREATE ON SCHEMA public FROM ${APP_USER};

-- Optional: If you want to restrict app_user from truncating tables
ALTER DEFAULT PRIVILEGES FOR USER ${MIGRATION_USER} IN SCHEMA public 
    REVOKE TRUNCATE ON TABLES FROM ${APP_USER};
REVOKE TRUNCATE ON ALL TABLES IN SCHEMA public FROM ${APP_USER};
EOSQL
