- name: Install and configure fail2ban
  vars:
    fail2ban_jail_config:
      DEFAULT:
        bantime: 1h
        findtime: 10m
        maxretry: 5
        banaction: nftables-multiport
        backend: systemd
        ignoreip: 127.0.0.1/8 ::1
      sshd:
        enabled: 'true'
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 3
        findtime: 5m
        bantime: 2h

  block:
    - name: Install fail2ban
      package:
        name: fail2ban
        state: present

    - name: Create fail2ban config directory
      file:
        path: /etc/fail2ban/filter.d
        state: directory
        mode: '0755'

    - name: Configure fail2ban jail local settings
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        mode: '0644'

    - name: Ensure fail2ban is started and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes
